In [26]:
import numpy as np
from random import random

In [48]:
arr = np.ones([5, 5])
print(arr,"\n\n")
arr[1:4,1:4:] = 0
arr[2:3,2:3:] = 9
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:

arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(f"Original 3D array:\n{arr_3d}\n")
print(f"Shape of the 3D array: {arr_3d.shape}\n")


sum_along_axis_2 = np.sum(arr_3d, axis=2)
print(f"Sum along axis 2:\n{sum_along_axis_2}\n")
print(f"Shape after summing along axis 2: {sum_along_axis_2.shape}\n")

Original 3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Shape of the 3D array: (2, 2, 3)

Sum along axis 2:
[[ 8 10 12]
 [14 16 18]]

Shape after summing along axis 2: (2, 3)

