In [3]:
import numpy as np

### Advanced Indexing

Advanced indexing refers to using arrays (integer or boolean) to select elements from another array. Unlike regular slicing, which always returns views, advanced indexing always returns copies of the data.

#### Two Main Types:

* **Integer array indexing:** Use arrays/lists of integer indices to get elements at specific positions.
* **Boolean array indexing:** Use boolean arrays (True/False) to select elements that meet a condition.

In [4]:
# 2D Integer Indexing
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
rows = [0, 1, 2]
cols = [2, 1, 0]
selected = arr[rows, cols] 
selected


array([3, 5, 7])

In [5]:
#  2D Boolean Indexing
arr = np.array([[5, 8], [15, 23], [42, 7]])
mask = arr > 10
selected = arr[mask]
print(selected)

[15 23 42]


In [6]:
age = np.array([22, 29, 17, 35, 14])
mask = age >= 18
is_adult = np.where(mask)
adults = age[is_adult]
adults

array([22, 29, 35])

In [7]:
A = np.array([[1,2,3],
              [4,5,6]])    # shape (2,3)
v = np.array([10,20,30])  # shape (3,)
print(A + v)

[[11 22 33]
 [14 25 36]]


In [8]:
A = np.array([[1,2,3],
              [4,5,6]])       # shape (2,3)
c = np.array([100, 200])       # shape (2,)
c_column = c[:, np.newaxis]
print(A + c_column)

[[101 102 103]
 [204 205 206]]


#### nditer for Efficient Iteration
 Modify array in-place using nditer

In [9]:
A = np.arange(6).reshape(2,3)
with np.nditer(A, op_flags=['readwrite']) as it:
    for x in it:
        x[...] = x * 2 
A

array([[ 0,  2,  4],
       [ 6,  8, 10]])

__Normalization__

subtract the mean from each column in a matrix:

- axis=0 operates on columns (vertical dimension).
- axis=1 operates on rows (horizontal dimension).

In [10]:
data = np.array([[1, 2], [3, 4], [5, 6]])
mean = data.mean(axis=0)
result = data - mean
result

array([[-2., -2.],
       [ 0.,  0.],
       [ 2.,  2.]])

In [11]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
for x in np.nditer(arr2d, flags=['external_loop']):
    print(x)
    
#each iteration yields a 1D array instead of single elements

[1 2 3 4 5 6]


In [12]:
# broadcasting iteration over multiple operands
A = np.array([[1,2,3],[4,5,6]])  # (2,3)
b = np.array([10,20,30])         # (3,)
# With Python loops:
for row in A:
    print(row + b)               # b broadcasts across each row

# with nditer pairing elements:
for x,y in np.nditer([A, b]):
    print(int(x), int(y))       


[11 22 33]
[14 25 36]
1 10
2 20
3 30
4 10
5 20
6 30


ravel (view) vs flatten (copy)

In [13]:
b = np.arange(6).reshape(2,3)
r = b.ravel()
f = b.flatten()
r[0] = 99
print(b[0,0])   # 99  (r is a view)
f[1] = -1
print(b[0,1])   # 1   (f is a copy)
print(np.may_share_memory(r, b))
print(np.may_share_memory(r, f))

# choose ravel when you want low-overhead view; 
# choose flatten to avoid accidental modification of original.

# ravel may return copy for non-contiguous arrays (e.g., after transpose). Do not assume it is always a view.

99
1
True
False


In [14]:
# swapaxes on 3D
arr3 = np.zeros((2,3,4))
b = arr3.swapaxes(0,2)
b.shape

# swap depth/height axes for image processing or model input.

(4, 3, 2)

In [15]:
x = np.ones((10, 3, 32, 32))   
y = np.rollaxis(x, 1, 4)
y.shape

(10, 32, 32, 3)

In [16]:
v = np.array([1,2,3])        
v_row = v[np.newaxis, :]     
v_col = v[:, np.newaxis]   
print(v_row.shape)
print(v_col.shape)
v.shape

(1, 3)
(3, 1)


(3,)

In [17]:
a = np.array([1,2,3])        #  (3,)
B = np.broadcast_to(a, (4,3)) 
print(a)
print(B)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [18]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.concatenate([a,b], axis=0)  
# np.add(a, b)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
x = np.array([1,2])
y = np.array([3,4])
print(np.stack([x,y], axis=0))   
print(np.stack([x,y], axis=1))

# np.stack(..., axis=n) inserts a new dimension at index n

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


- For a 2D array, let's take z = np.array([[1, 2], [3, 4]]). The shape is (2, 2).

z.sum(axis=0)
- Action: This sums along the rows (the vertical direction), collapsing the 0th axis. It calculates the sum for each column.
- Result: [1+3, 2+4] → [4, 6]

z.sum(axis=1)
- Action: This sums across the columns (the horizontal direction), collapsing the 1st axis. It calculates the sum for each row.
- Result: [1+2, 3+4] → [3, 7] 

#### BINARY OPERATORS

In [20]:
print(np.bitwise_and(13, 17)) 
a = np.array([13, 7])
b = np.array([17, 14]) 
print(np.bitwise_and(a, b))

1
[1 6]


In [21]:
a = np.array([13, 7])
b = np.array([17, 14])
print(np.bitwise_or(a, b))

[29 15]


In [22]:
print(np.left_shift(10, 2))   
print(np.right_shift(40, 2))  


40
10


In [23]:
print(np.char.add(['Hello', 'Good'], [' World', ' Morning']))
print(np.char.join(':', 'PYTHON'))

['Hello World' 'Good Morning']
P:Y:T:H:O:N


In [24]:
arr = np.array([1.23, 5.67, 2.49])
print(np.around(arr))  
print(np.floor(arr))   
print(np.ceil(arr)) 

[1. 6. 2.]
[1. 5. 2.]
[2. 6. 3.]


##### STATISTICAL FUNCTIONS

In [25]:
a = np.array([[1,2,3],[4,5,6]])
print(np.amin(a))             # 1
print(np.amax(a, axis=0))

1
[4 5 6]


In [26]:
a = np.array([4, 9, 7, 6, 3, 8])
print(np.ptp(a)) 

# measures data range

6


In [27]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a, 50)) # median 

5.0


In [28]:
a = np.array([1,2,3,4,5])
print(np.median(a))   
print(np.mean(a))     
print(np.average(a, weights=[1,1,1,1,6])) 

3.0
3.0
4.0


##### SORT, SEARCH & COUNTING FUNCTIONS

In [29]:
# np.argsort() determines where each element of the sorted array comes from in the original array
x = np.array([3, 1, 6, 4, 3])
print(np.argsort(x)) 
print(x[np.argsort(x)])  

[1 0 4 3 2]
[1 3 3 4 6]


In [30]:
# Finds index positions where elements should be inserted to maintain order

arr = np.array([1, 2, 4, 7])
print(np.searchsorted(arr, 5))  #

3


In [31]:
# Finds elements where it is is Non-Zero

arr = np.array([[0,1,2],[0,0,3]])
print(np.count_nonzero(arr))

3


In [32]:
mat = np.matrix('1 2; 3 4')
print(mat)

[[1 2]
 [3 4]]


In [33]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.linalg.det(a))  # Determinant
print(np.linalg.inv(a)) # Inverse

# vals, vecs = np.linalg.eig(a)
# print("Eigenvalues:", vals)
# print("Eigenvectors:\n", vecs)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [34]:
arr = np.arange(24).reshape(2, 3, 4)
print(arr)
np.delete(arr, 2, 1)
# np.expand_dims(arr, axis=1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19]]])

In [35]:
arr = np.array([1, 2, 2, 3, 3, 3])
unique = np.unique(arr)
unique


array([1, 2, 3])

#### Why use Matplotlib with NumPy?

* Visualize numerical data for better understanding.
* Plot functions, datasets, histograms, bar charts, and more.
* Supports integration with NumPy arrays seamlessly.

In [36]:
import matplotlib.pyplot as plt

In [37]:

# x = np.linspace(0, 10, 100) 
# y = np.sin(x)                # sine of x
# plt.plot(x, y)               # plot x vs y
# plt.xlabel('x')
# plt.ylabel('sin(x)')
# plt.title('Plot of sin(x)')
# plt.show()


np.int64(176)