In [ ]:
import numpy as np

##### NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.
- Speed: numerical operations are implemented in C/Fortran; vectorized operations avoid Python loops and their overhead.

Most NumPy arrays have some restrictions. For instance:

- All elements of the array must be of the same type of data.

- Once created, the total size of the array can’t change.

- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a

- If dtype is 8 bytes and shape is (2,3) (2 rows, 3 cols), then:

- stride[1] = 8 bytes to move one column (next element in a row).

- stride[0] = 3 * 8 = 24 bytes to move one row (skip 3 elements).
- So offset for index (i,j) from base pointer = i*stride[0] + j*stride[1].

In [ ]:
a = np.array([[1, 2, 3],
             [4, 5, 6]], dtype=np.int64)

print(a.shape)
print(a.ndim)
print(a.strides)
print(a.size)
print(a.dtype)
print(a.nbytes)
print(a.itemsize)

In [ ]:
elements = np.linspace(0, 10, num=21) 
print(elements)
elements = np.zeros((2,3))   
print(elements)
elements = np.ones((2,3))   
print(elements)
np.arange(0, 10, 2)    


In [50]:
elements = np.full((3,3), 7) 
print(elements) 
elements = np.identity(3) 
print(elements) 
np.eye(3)
elements = np.diag([1,2,3])   
print(elements)



[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


Use .astype() to cast: a.astype(np.float32). Casting creates a new array.

In [ ]:
x = np.arange(11) 
print(x[2:7])
print(x[::2])

In [ ]:
components = np.arange(12).reshape(3, 4)
print(components,"\n")
print(components[0:3, 1:3])

Slicing returns a view, not a copy (most of the time).

In [ ]:
arr = np.arange(10)
s = arr[2:6] # .copy()
s[0] = 40

arr

In [ ]:
elements = 

@ or np.dot() is matrix multiplication for 2D arrays.

In [ ]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(a + b)
print(a * 2)
print(a @ b)
print(np.dot(a, b))

print(np.sin(a))

- _Vectorization_: instead of writing Python loops, use array ops — NumPy does the *heavy lifting in C*. This is the primary reason for speed-ups.

- _Ufuncs_: fast element-wise functions (np.add, np.sin, np.exp, np.maximum, etc.). They often have extra methods like .reduce, .accumulate

In [ ]:
arr = np.array(
    list(set([1,2,3,4]))
)
arr[0]


In [35]:
A = np.ones((3,4))
print(A)
b = np.arange(4)
print(b)
A + b 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
s = arr[2:5]
s.base is arr

- Slicing is a view — modifying a slice modifies the original.

- np.append is inefficient — it creates a new array repeatedly (not like list.append). Use lists and then np.array() or pre-allocate and fill.

- np.arange with floats can give surprising endpoints due to float rounding; use linspace for exact num points.

- Integer division vs true division: / yields floats (true division), // yields floor division (result dtype depends).

- Boolean indexing returns a copy, not a view. E.g. b = a[a>0] is a copy.

- Non-contiguous arrays (e.g., transposed views) may be slower; np.ascontiguousarray() can help.

- Data type overflow: integer arrays wrap on overflow (no error). Be mindful of dtype range.

- Using object dtype kills vectorization; avoid unless necessary.

In [ ]:
lst = [1,2,3]
arr = np.asarray(lst)
arr2 = np.asarray(arr) 
print(arr)
print(arr2)

In [77]:
elements = np.linspace(0, 10, num=15)
print(elements)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [66]:
arr1 = np.ones((3,3))
np.fill_diagonal(arr1, 0)
print(arr1)

[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
